### ISSUE TITLE
Multiplayer lobby player pass info only outputting False

### ISSUE THREAD

**Issue by Beyley** [Xferno2/CSharpOsu#6]
So, i'm writing a program to grab all the info relating to a multiplayer match, i have everything but the bool relating to whether a player has passed the multiplayer match, 
`OsuMatch match = new OsuMatch();
match = osu.GetMatch(MATCH-ID);
Console.WriteLine(match.games[0].scores[0].pass)`
this always outputs False, even if i use debugging to view the variables state, every players "pass" value is set to false

**Comment by Xferno2** [comment]
I'm looking into it right now.

**Comment by Xferno2** [comment]
I have fixed the code. Should display the correct bool now. You'll have to build the project yourself to get the fix .The fix will be included in the next nuget version that I'm working on.
