### ISSUE TITLE
OsuBeatmap attributes should be written capitalized.

### ISSUE THREAD

**Issue by takoz53** [Xferno2/CSharpOsu#8]
beatmap.artist → beatmap.Artist
beatmap.difficulty → beatmap.Difficulty

Somehow yet "StarRating" is written capitalized. On {get; set;} you should always capitalize.

**Comment by Xferno2** [comment]
That's not the case only for beatmap attributes, there are not capitalized attributes in other models as well. I will rewrite their names once I finish more important matters.
